project_id = "mhlyndipnpwpcydjukig"

[functions.gtfs-proxy]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.check-trip-reminders]
verify_jwt = false

[functions.check-delays]
verify_jwt = false

[functions.check-stop-arrivals]
verify_jwt = false

[functions.generate-vapid-keys]
verify_jwt = false

[functions.test-push]
verify_jwt = false
